apiVersion: v1
kind: Secret
metadata:
  name: b2-keys
  namespace: your-ns # change me
data:
  keyID: YourKeyID # change me - base 64 encoded key ID
  applicationKey: YourKey # change me - base64 encoded application key
  resticKey: YourEncKey # change me - base64 encoded encryption key (generate randomly)
  bucketName: "b2:your-bucket" # change me - prefix your bucket name with b2:
type: Opaque