apiVersion: batch/v1
kind: CronJob
metadata:
  name: restic-backup
  namespace: your-ns  # Change me
spec:
  concurrencyPolicy: Forbid
  schedule: "12 2 * * *"  # Change me if needed (02:12 daily)
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: restic
            image: restic/restic:latest
            args:
              - backup
              - /data
            env:
              - name: RESTIC_REPOSITORY
                valueFrom:
                  secretKeyRef:
                    name: s3-keys
                    key: bucketName
                    optional: false
              - name: RESTIC_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: s3-keys
                    key: resticKey
                    optional: false
              - name: AWS_ACCESS_KEY_ID
                valueFrom:
                  secretKeyRef:
                    name: s3-keys
                    key: accessKeyId
                    optional: false
              - name: AWS_SECRET_ACCESS_KEY
                valueFrom:
                  secretKeyRef:
                    name: s3-keys
                    key: secretAccessKey
                    optional: false
            volumeMounts:
              - name: backupdata
                mountPath: /data
                readOnly: true
          volumes:
            - name: backupdata
              persistentVolumeClaim:
                claimName: your-pvc  # Change me
          restartPolicy: OnFailure